services:
  postgres:
    image: postgres:16.2-alpine
    container_name: postgres_users
    restart: always
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "users" ]
      interval: 10s
      timeout: 10s
      retries: 5
